name: 'Code Format Check'
description: 'Run set up python, pre-commit, and auto-commit changes'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

    - name: Auto-commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      if: always()
      with:
        commit_message: Apply code-format changes
        commit_user_name: flagtree-bot
        commit_user_email: flagtree_ai@163.com
        commit_author: flagtree-bot <flagtree_ai@163.com>
