name: Hcu3.6-Build-And-Test

on:
  push:
    branches: [ "main", "triton_v3.6.x" ]
  pull_request:
    branches: [ "main", "triton_v3.6.x" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  hcu36x-unit-test:
    runs-on: hcu3.6
    if: ${{ github.repository == 'FlagTree/flagtree' || github.repository == 'flagos-ai/flagtree' }}
    steps:
      - name: Setup environment
        shell: bash
        run: |
          source ~/env.sh
          env | grep -E '^(http_proxy|https_proxy|all_proxy|no_proxy)=' >> $GITHUB_ENV || true

      - name: Smart Checkout
        uses: flagos-ai/FlagTree/.github/actions/smart-checkout@main
        with:
          checkout_version: 'v6'

      - name: Check if backend-relevant files changed
        id: check_backend
        uses: flagos-ai/FlagTree/.github/actions/check-backend-changed@main
        with:
          backend: hcu

      - name: Build FlagTree
        if: steps.check_backend.outputs.should_skip != 'true'
        shell: bash
        run: |
          set -x
          export FLAGTREE_BACKEND=hcu
          MAX_JOBS=32 python3 -m pip install . --no-build-isolation

      - name: Unit Test
        if: steps.check_backend.outputs.should_skip != 'true'
        shell: bash
        run: |
          set -x
          source ~/env.sh
          python3 -m pytest -s third_party/hcu/python/test/unit
          python3 -m pytest -s python/test/tle/integration/test_tle_local_store.py
          python3 -m pytest -s python/test/tle/integration/test_tle_gemm.py
          python3 -m pytest -s python/test/tle/integration/test_tle_pipeline_e2e.py
          python3 -m pytest -s python/test/tle/unit/test_tle_gpu_local_ptr.py
          python3 -m pytest -s python/test/tle/unit/test_tle_gpu_slot.py
